<a href="https://colab.research.google.com/github/shikha-geeka-chad/Create_LoginPage/blob/main/torchtutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [12]:
x = torch.tensor([1.0], dtype=torch.int64)
x

tensor([1])

In [11]:
x.dtype

torch.int64

In [13]:
device = torch.cuda.is_available()

In [14]:
import torch

# creation
x = torch.tensor([[1., 2.], [3., 4.]])     # float32 by default
y = torch.ones_like(x)                      # same shape/dtype/device
z = torch.arange(6).reshape(2, 3)

False

In [15]:
y = torch.zeros_like(x)
y

tensor([0])

In [18]:
z = torch.arange(6).reshape(6,1)

In [19]:
z

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5]])

In [20]:
x = x.to(torch.int32)                    # change dtype
device = "cuda" if torch.cuda.is_available() else "cpu"
x = x.to(device)

In [21]:
device

'cpu'

In [25]:
import numpy as np
x = np.random.standard_normal(size=20).reshape(4,5)
x

array([[-0.96320342, -0.14908726, -1.07112686,  1.17883573,  1.39933291],
       [ 0.24837331,  0.21715177, -0.32142586, -0.70670376, -1.36572805],
       [ 0.00478165,  0.43632811,  1.07525467,  1.58641519, -0.18198779],
       [-0.60540448,  0.12258413, -0.46872769, -0.84797837, -0.73935309]])

In [26]:
x1 = torch.tensor(x)

In [27]:
x1

tensor([[-0.9632, -0.1491, -1.0711,  1.1788,  1.3993],
        [ 0.2484,  0.2172, -0.3214, -0.7067, -1.3657],
        [ 0.0048,  0.4363,  1.0753,  1.5864, -0.1820],
        [-0.6054,  0.1226, -0.4687, -0.8480, -0.7394]], dtype=torch.float64)

In [28]:
x1 = torch.randn(4,5)
x1

tensor([[ 0.5197,  0.0589, -0.6697,  0.5513,  0.2234],
        [-0.1914,  0.0828, -0.6561, -0.9699, -0.7060],
        [-0.5836, -1.3900,  1.9545,  0.5830, -0.1151],
        [-0.5527, -0.2377, -0.9974,  1.3982, -0.0331]])

In [29]:
x1.mean(dim=0 )

tensor([-0.2020, -0.3715, -0.0922,  0.3907, -0.1577])

In [30]:
x1.mean(dim=1 )

tensor([ 0.1367, -0.4881,  0.0898, -0.0845])

In [31]:
x1.std(dim=0)

tensor([0.5131, 0.6945, 1.3736, 0.9881, 0.3929])

In [32]:
x1.std(dim=1 )

tensor([0.4956, 0.4248, 1.2655, 0.9052])

In [33]:
#Create a tensor of shape (3, 4) filled with random integers between 10 and 50.
x2 = torch.randint(10,50,(3,4))
x2

tensor([[38, 25, 42, 27],
        [40, 30, 39, 13],
        [10, 36, 20, 41]])

In [34]:
print(x2.shape, x2.ndim)          # size and number of dimensions
print(x2.dtype, x2.device)        # data type and where it lives

x = torch.arange(12)            # [0..11]
print(x.view(3, 4))             # reshape (shares memory)
print(x.reshape(2, 2, 3))       # reshape (may copy memory)


torch.Size([3, 4]) 2
torch.int64 cpu
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [36]:
#Make a (2, 3, 4) tensor of sequential numbers and flatten it back to (24,).
x = torch.arange(24).reshape(2,3,4)
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [37]:
x.flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [38]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [40]:
x = torch.arange(1, 13).view(3, 4)
print(x)
print(x[0, 1])          # single element
print(x[:, 2])          # 3rd column
print(x[1:])            # rows 1–end
print(x[:, ::2])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor(2)
tensor([ 3,  7, 11])
tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


In [41]:
x.shape

torch.Size([3, 4])

In [48]:
# x, extract the last two rows and the last column only.
x[(x.shape[0]-2):, x.shape[1]-1]

tensor([ 8, 12])

In [51]:
#Make two tensors of shapes (2, 1, 3) and (1, 4, 1) and compute their sum.

x1 = torch.arange(20,26).reshape(2,1,3)
x2 = torch.arange(4).reshape(1,4,1)
print(x1)
print(x2)
print(x1+x2)

tensor([[[20, 21, 22]],

        [[23, 24, 25]]])
tensor([[[0],
         [1],
         [2],
         [3]]])
tensor([[[20, 21, 22],
         [21, 22, 23],
         [22, 23, 24],
         [23, 24, 25]],

        [[23, 24, 25],
         [24, 25, 26],
         [25, 26, 27],
         [26, 27, 28]]])


In [53]:
x = torch.ones((2,3))
y = torch.zeros((2,3))
print(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [54]:
cat1 = torch.cat((x, y), dim=0)
cat2 = torch.cat((x, y), dim=1)

In [55]:
cat1

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [56]:
cat2

tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])

In [58]:
stacked = torch.stack((x, y), dim=0)  # (2,2,3)
stacked

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [60]:
stacked.shape

torch.Size([2, 2, 3])

In [61]:
stacked = torch.stack((x, y), dim=1)  # (2,2,3)
stacked

tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])

In [63]:
#Create two (3, 2) tensors and stack them along a new dimension so the result is (2, 3, 2).
x1 = torch.ones(3,2)
x2 = torch.zeros_like(x1)
print(x1)
print(x2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [68]:
stacked = torch.stack((x1,x2), dim = 0 )
stacked.shape

torch.Size([2, 3, 2])

In [69]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.randn(2, 3).to(device)
print(x.device)


cpu


In [71]:
#Create a (4, 4) tensor on GPU (if available), multiply it by 2, and move it back to CPU.

device = 'cuda' if torch.cuda.is_available() else 'cpu'
n = torch.zeros(4,4).to(device)
n= n*2
n= n.to('cpu')
n

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [80]:
x = torch.randn(4,5)
print(x.mean(dim=0))        # column means
print(x.std(dim=1))         # row std
print(x.sum())              # total sum
print(x.min(), x.max())     # scalars


tensor([-1.0652, -0.6212, -0.6171,  0.1923,  0.1090])
tensor([1.0427, 0.4506, 1.5865, 0.7094])
tensor(-8.0090)
tensor(-2.1129) tensor(2.0418)


In [81]:
print(x.mean(dim=1))

tensor([-0.4026,  0.0486, -0.5775, -0.6702])


In [73]:
#Compute the mean for each row and verify by x.mean(dim=1).
x

tensor([[-1.5723, -0.3909, -0.7930, -0.4523,  0.6845],
        [-1.0739, -0.2546,  0.7273,  1.7682,  0.7150],
        [-1.6884,  1.1439, -0.8926, -0.8648, -1.1210],
        [-0.5173,  1.6803,  0.6368, -0.7389, -0.6577]])

In [83]:
n = x.shape[0]
val = []
for i in range(n):
    val.append(x[i, :].mean())  # Use 'i' not 'n'

In [84]:
val

[tensor(-0.4026), tensor(0.0486), tensor(-0.5775), tensor(-0.6702)]

In [86]:
x = torch.ones(3)
y = x
print(y)
print(x)
x.add_(5)         # in-place (notice the underscore)
print(y)
print(x)

tensor([1., 1., 1.])
tensor([1., 1., 1.])
tensor([6., 6., 6.])
tensor([6., 6., 6.])


In [87]:
#Experiment with x.mul_(2) vs x * 2.
#What happens to the original x?
x = torch.ones(3)
print(x)
x.mul_(2)
print(x)


tensor([1., 1., 1.])
tensor([2., 2., 2.])


In [88]:
x = torch.ones(4)
print(x)
x*2

tensor([1., 1., 1., 1.])


tensor([2., 2., 2., 2.])

In [89]:
x

tensor([1., 1., 1., 1.])

In [90]:
import numpy as np
arr = np.array([[1, 2, 3]])
t = torch.from_numpy(arr)
arr[0,0] = 99
print(t)              # reflects the change (shared memory)


tensor([[99,  2,  3]])


In [91]:
#Create three tensors of shape (2, 2) and concatenate them along rows (dim = 0).

In [97]:
x1 = torch.randint(2,10 , size=(2,2))
x2 = torch.ones(2,2)
x3 = torch.zeros(2,2)

f = torch.cat((torch.cat((x1,x2) , dim = 0),x3) , dim =0 )
f

tensor([[6., 7.],
        [3., 6.],
        [1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]])

In [99]:
#Stack three (2, 2) tensors along a new last dimension (dim=-1).
x1 = torch.randint(2,10 , size=(2,2))
x2 = torch.ones(2,2)
x3 = torch.zeros(2,2)

torch.stack((x1,x2,x3), dim = -1 ).shape

torch.Size([2, 2, 3])

In [105]:
x1, x2 , x3

(tensor([[2, 8],
         [3, 8]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[0., 0.],
         [0., 0.]]))

In [100]:
torch.stack((x1,x2,x3), dim = -1 )

tensor([[[2., 1., 0.],
         [8., 1., 0.]],

        [[3., 1., 0.],
         [8., 1., 0.]]])

In [101]:
torch.stack((x1,x2,x3), dim = 0 )

tensor([[[2., 8.],
         [3., 8.]],

        [[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.]]])

In [102]:
torch.stack((x1,x2,x3), dim = 1 )

tensor([[[2., 8.],
         [1., 1.],
         [0., 0.]],

        [[3., 8.],
         [1., 1.],
         [0., 0.]]])

In [103]:
torch.stack((x1,x2,x3), dim = 2 )

tensor([[[2., 1., 0.],
         [8., 1., 0.]],

        [[3., 1., 0.],
         [8., 1., 0.]]])

In [106]:
x = torch.arange(10)
parts = torch.split(x, 3)   # sizes (3,3,3,1)
for p in parts:
    print(p)


tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])
tensor([9])
